#include "game_ids.h"

/* ── Real-tileset tile data (game content, banked ROM) ─────────────
 * Generated by tools/png2gb.py (make gfx) with --global so the arrays are
 * linkable across translation units.  ui.c loads them into VRAM at boot via
 * banked_copy() (ui_gfx_load, called from game_init after banked_copy_init),
 * and never reads banked data directly.  This mirrors how the event and
 * dialogue content tables are banked. */

#pragma bank 2

#include "gfx/battle_bg.h"
#include "gfx/ui_frame.h"
#include "gfx/enemy_slime.h"
#include "gfx/enemy_bat.h"
#include "gfx/enemy_boss.h"
