#include "ui.h"
#include "actor.h"
#include "scene.h"
#include <gb/gb.h>
#include <gb/cgb.h>
#include <gbdk/font.h>
#include <gbdk/console.h>
#include <stdio.h>

char g_ui_screen_buf[18][21];

/* GBDK console .mode byte (defined in crt0.s _DATA). Bit 2 is M_NO_SCROLL. */
extern uint8_t console_mode;

static void ui_put_char(uint8_t x, uint8_t y, char ch);
static void ui_draw_num2(uint8_t x, uint8_t y, uint8_t val);

static font_t ibm_font;

static const palette_color_t cgb_palette[4] = {
    RGB8(255, 255, 255),
    RGB8(170, 170, 170),
    RGB8(85, 85, 85),
    RGB8(0, 0, 0)
};

/* ── Player sprite ─────────────────────────────────────────────────
 * Tile data is generated by tools/png2gb.py from assets/player_demo.png
 * (make gfx); see docs/graphics.md.  The array is included verbatim. */
#include "gfx/player_sprite_tile.h"

#define PLAYER_SPRITE_NUM 0
#define PLAYER_SPRITE_TILE_ID 0

void ui_init(void)
{
    /* Turn the LCD off before loading the font so that display_off() inside
     * set_bkg_data() returns immediately (it waits for VBlank otherwise).
     * The CRT0 boot already leaves the LCD off; the harness (which skips
     * CRT0) needs this too, and mGBA's debugger does not advance VBlank
     * during single-stepping. */
    LCDC_REG &= ~0x80;

    font_init();
    ibm_font = font_load(font_ibm);
    font_set(ibm_font);

    /* Disable GBDK console auto-scroll.  When putchar() advances the cursor
     * past the bottom-right tile, the console normally scrolls the whole
     * screen up one line.  M_NO_SCROLL (bit 2 of the console .mode byte,
     * exposed as console_mode by crt0.s) makes it reset the cursor instead. */
    console_mode |= M_NO_SCROLL;

    /* Set DMG palettes: 0xE4 = 11 10 01 00 (Lightest to Darkest) */
    BGP_REG = 0xE4;
    OBP0_REG = 0xE4;
    OBP1_REG = 0xE4;

    /* Set CGB Palette 0 if running on CGB hardware */
    if (_cpu == CGB_TYPE) {
        set_bkg_palette(0, 1, cgb_palette);
    }

    SHOW_BKG;
    ui_sprite_init();
    DISPLAY_ON;
}

/* Load the player sprite tile and enable the OAM sprite.  Called from
 * ui_init() while the LCD is still off: set_sprite_data() writes VRAM
 * through the same path as set_bkg_data() (both live in set_data.o) and
 * returns immediately while the LCD is off, so this stays harness-safe
 * (AGENTS.md 52.6).  The sprite starts hidden (OAM Y = 0); the overworld
 * render positions it via ui_sprite_move(). */
void ui_sprite_init(void)
{
    set_sprite_data(PLAYER_SPRITE_TILE_ID, 1, player_sprite_tile);
    set_sprite_tile(PLAYER_SPRITE_NUM, PLAYER_SPRITE_TILE_ID);
    SPRITES_8x8;
    SHOW_SPRITES;
    hide_sprite(PLAYER_SPRITE_NUM);
}

/* Position the player sprite over background tile (map_x, map_y).
 * Hardware OAM coordinates are offset +8/+16 from the visible tile grid
 * (GBDK's move_sprite takes raw OAM coordinates, not screen tiles); a
 * valid position (y >= 16) also un-hides the sprite. */
void ui_sprite_move(uint8_t map_x, uint8_t map_y)
{
    move_sprite(PLAYER_SPRITE_NUM, (uint8_t)(map_x * 8 + 8), (uint8_t)(map_y * 8 + 16));
}

/* Hide the player sprite (OAM Y = 0).  Called on transitions away from the
 * overworld so the blob does not float over battle/menu screens. */
void ui_sprite_hide(void)
{
    hide_sprite(PLAYER_SPRITE_NUM);
}

void ui_clear_screen(void)
{
    uint8_t x, y;
    for (y = 0; y < 18; y++) {
        for (x = 0; x < 20; x++) {
            gotoxy(x, y);
            putchar(' ');
            g_ui_screen_buf[y][x] = ' ';
        }
        g_ui_screen_buf[y][20] = '\0';
    }
}

void ui_draw_text_line(uint8_t x, uint8_t y, const char *text, uint8_t max_chars)
{
    uint8_t i = 0;
    char ch;
    gotoxy(x, y);
    if (text) {
        while (text[i] != '\0' && i < max_chars) {
            ch = text[i];
            putchar((int)ch);
            if (y < 18 && (x + i) < 20) {
                g_ui_screen_buf[y][x + i] = ch;
            }
            i++;
        }
    }
    while (i < max_chars) {
        putchar(' ');
        if (y < 18 && (x + i) < 20) {
            g_ui_screen_buf[y][x + i] = ' ';
        }
        i++;
    }
}

void ui_format_int(int16_t value, char *out)
{
    char tmp[7];
    uint8_t i = 0;
    uint8_t j = 0;
    int32_t mag;
    int16_t digit;

    if (!out) return;
    mag = (value < 0) ? -(int32_t)value : (int32_t)value;

    if (mag == 0) {
        tmp[i++] = '0';
    }
    while (mag > 0) {
        digit = (int16_t)(mag % 10);
        tmp[i++] = (char)('0' + digit);
        mag /= 10;
    }
    if (value < 0) {
        tmp[i++] = '-';
    }
    while (i > 0) {
        out[j++] = tmp[--i];
    }
    out[j] = '\0';
}

void ui_draw_world_map(const World *world)
{
    uint8_t x, y;
    uint8_t t;
    char tile_ch;
    const WorldActorDefinition *actor;
    const SceneExit *ex;

    if (!world) return;

    /* The player is no longer painted into the background at all (see
     * ui_sprite_move): background tiles are drawn for every cell, including
     * the player's own cell, and the OAM sprite sits visually on top of it.
     * This is the actual BG-tilemap / OAM-sprite split a real Game Boy
     * renderer uses; it just happens that the "tilemap" here is still the
     * ASCII console font. */
    for (y = 0; y < WORLD_VIEW_HEIGHT; y++) {
        for (x = 0; x < WORLD_WIDTH; x++) {
            actor = actor_find_at(world, x, y);
            if (actor) {
                tile_ch = actor->visual;
            } else {
                t = world->map[y][x];
                if (t == TILE_WALL) tile_ch = '#';
                else if (t == TILE_BUILDING) tile_ch = 'B';
                else if (t == TILE_EXIT) {
                    ex = scene_exit_at(scene_definition_for_map(world->map_id), x, y);
                    tile_ch = ex ? ex->tile_char : '.';
                } else tile_ch = '.';
            }
            gotoxy(x, y);
            putchar(tile_ch);
            g_ui_screen_buf[y][x] = tile_ch;
        }
    }

    ui_sprite_move(world->player.position.x, world->player.position.y);
}

void ui_draw_overworld_hud(const World *world)
{
    const char *label;

    if (!world) return;

    switch (world->map_id) {
        case MAP_TOWN:          label = "MAP: TOWN | HP:";  break;
        case MAP_FOREST:        label = "MAP: FORST| HP:";  break;
        case MAP_MOUNTAIN_PASS: label = "MAP: MOUNT| HP:";  break;
        case MAP_CASTLE:        label = "MAP: CASTL| HP:";  break;
        default:                label = "MAP: FIELD| HP:";  break;
    }

    ui_draw_text_line(0, 12, "====================", 20);
    ui_draw_text_line(0, 13, label, 15);
    ui_draw_num2(15, 13, world->player.hp);
    ui_put_char(17, 13, '/');
    ui_draw_num2(18, 13, world->player.max_hp);
    ui_draw_text_line(0, 14, "", 20);
    ui_draw_text_line(0, 15, "", 20);
    ui_draw_text_line(0, 16, "", 20);
    ui_draw_text_line(0, 17, " [D-PAD] MOVE HERO", 20);
}

void ui_draw_world_full(const World *world)
{
    if (!world) return;
    ui_clear_screen();
    ui_draw_world_map(world);
    ui_draw_overworld_hud(world);
}

void ui_update_player_position(const World *world, uint8_t old_x, uint8_t old_y, uint8_t new_x, uint8_t new_y)
{
    /* The background never encodes the player (see ui_draw_world_map), so
     * there is nothing to erase/redraw at old_x/old_y any more -- moving
     * the OAM sprite is the whole update.  old_x/old_y are kept in the
     * signature so callers (RenderCache in overworld_screen.c) don't need
     * to change. */
    (void)old_x;
    (void)old_y;
    if (!world) return;
    ui_sprite_move(new_x, new_y);
}

static void ui_put_char(uint8_t x, uint8_t y, char ch)
{
    gotoxy(x, y);
    putchar((int)ch);
    if (y < 18 && x < 20) {
        g_ui_screen_buf[y][x] = ch;
    }
}

/* Draw a value right-aligned in a 2-wide field (space padded) at (x,y). */
static void ui_draw_num2(uint8_t x, uint8_t y, uint8_t val)
{
    char c;
    if (val >= 10) {
        c = '0' + (val / 10);
    } else {
        c = ' ';
    }
    ui_put_char(x, y, c);
    ui_put_char(x + 1, y, '0' + (val % 10));
}

/* Draw a battle HP line: "  HP: <hp>/<max>" at row y. */
static void ui_draw_hp_row(uint8_t y, uint8_t hp, uint8_t max_hp)
{
    ui_draw_text_line(0, y, "  HP: ", 6);
    ui_draw_num2(6, y, hp);
    ui_put_char(8, y, '/');
    ui_draw_num2(9, y, max_hp);
}

void ui_draw_battle_full(const Battle *battle)
{
    if (!battle) return;

    ui_clear_screen();

    ui_draw_text_line(0, 0, "====================", 20);
    ui_draw_text_line(0, 1, "    BATTLE ENCOUNTER", 20);
    ui_draw_text_line(0, 2, "====================", 20);

    ui_draw_text_line(0, 5, "  ENEMY: ", 9);
    ui_draw_text_line(9, 5, battle->enemy.name ? battle->enemy.name : "ENEMY", 8);
    ui_draw_hp_row(6, battle->enemy.hp, battle->enemy.max_hp);

    ui_draw_text_line(0, 9, "  HERO:  HERO [@]", 20);
    ui_draw_hp_row(10, battle->player.hp, battle->player.max_hp);

    ui_draw_text_line(0, 13, "--------------------", 20);

    ui_update_battle(battle);
}

void ui_update_battle(const Battle *battle)
{
    if (!battle) return;

    /* Keep HP readouts current as damage is dealt/received */
    ui_draw_hp_row(6, battle->enemy.hp, battle->enemy.max_hp);
    ui_draw_hp_row(10, battle->player.hp, battle->player.max_hp);

    if (battle->result == BATTLE_RESULT_VICTORY) {
        ui_draw_text_line(0, 15, " VICTORY! PRESS [A]", 20);
    } else if (battle->result == BATTLE_RESULT_DEFEAT) {
        ui_draw_text_line(0, 15, " DEFEATED! PRESS [A]", 20);
    } else if (battle->result == BATTLE_RESULT_FLED) {
        ui_draw_text_line(0, 15, " FLED! PRESS [A]", 20);
    } else if (battle->turn == BATTLE_TURN_PLAYER) {
        ui_draw_text_line(0, 15, " [A] ATTACK  [B] RUN", 20);
    } else {
        ui_draw_text_line(0, 15, " ENEMY TURN...", 20);
    }
}

void ui_draw_dialogue(const DialogueState *dialogue)
{
    if (!dialogue || !dialogue->active) return;
    if (dialogue->current_line >= dialogue->line_count) return;

    /* Dialogue box occupies dedicated modal overlay region: rows 12-17 (6 rows, 20 columns) */
    ui_draw_text_line(0, 12, "+------------------+", 20);

    gotoxy(0, 13);
    putchar('|');
    g_ui_screen_buf[13][0] = '|';
    ui_draw_text_line(1, 13, dialogue->speaker ? dialogue->speaker : "", 18);
    gotoxy(19, 13);
    putchar('|');
    g_ui_screen_buf[13][19] = '|';

    gotoxy(0, 14);
    putchar('|');
    g_ui_screen_buf[14][0] = '|';
    ui_draw_text_line(1, 14, dialogue->lines[dialogue->current_line], 18);
    gotoxy(19, 14);
    putchar('|');
    g_ui_screen_buf[14][19] = '|';

    gotoxy(0, 15);
    putchar('|');
    g_ui_screen_buf[15][0] = '|';
    ui_draw_text_line(1, 15, "", 18);
    gotoxy(19, 15);
    putchar('|');
    g_ui_screen_buf[15][19] = '|';

    gotoxy(0, 16);
    putchar('|');
    g_ui_screen_buf[16][0] = '|';
    ui_draw_text_line(1, 16, " [A] CONTINUE", 18);
    gotoxy(19, 16);
    putchar('|');
    g_ui_screen_buf[16][19] = '|';

    ui_draw_text_line(0, 17, "+------------------+", 20);
}

void ui_draw_game_over(uint8_t choice)
{
    ui_clear_screen();
    ui_draw_text_line(0, 3, "    GAME OVER", 20);
    ui_draw_text_line(0, 8, "   CONTINUE?", 20);
    if (choice == 0) {
        ui_draw_text_line(0, 11, "> YES", 20);
        ui_draw_text_line(0, 12, "  NO", 20);
    } else {
        ui_draw_text_line(0, 11, "  YES", 20);
        ui_draw_text_line(0, 12, "> NO", 20);
    }
    ui_draw_text_line(0, 16, " [A] CONFIRM", 20);
}

void ui_draw_thanks(void)
{
    ui_clear_screen();
    ui_draw_text_line(0, 8, " THANKS FOR PLAYING!", 20);
}

#ifdef DEBUG_BUILD
void ui_draw_font_test(void)
{
    ui_clear_screen();
    ui_draw_text_line(0, 0, "=== FONT TEST ===", 20);
    ui_draw_text_line(0, 2, "ABCDEFGHIJKLMNOPQRST", 20);
    ui_draw_text_line(0, 4, "UVWXYZ", 20);
    ui_draw_text_line(0, 6, "abcdefghijklmnopqrst", 20);
    ui_draw_text_line(0, 8, "uvwxyz", 20);
    ui_draw_text_line(0, 10, "0123456789", 20);
    ui_draw_text_line(0, 12, "!?.,:-'[]+=", 20);
}
#endif
