#include "ui.h"
#include "actor.h"
#include "scene.h"
#include <gb/gb.h>
#include <gb/cgb.h>
#include <gbdk/font.h>
#include <gbdk/console.h>
#include <stdio.h>

char g_ui_screen_buf[18][21];

#ifdef DEBUG_BUILD
/* Mirror of the background tilemap ring (0x9800), written alongside every
 * ring write, so the harness can assert the actual rendered map (mGBA's
 * debugger cannot read VRAM).  DEBUG-only: 1 KB of WRAM the release does
 * not carry. */
uint8_t g_tilemap_mirror[32 * 32];
#endif

/* GBDK console .mode byte (defined in crt0.s _DATA). Bit 2 is M_NO_SCROLL. */
extern uint8_t console_mode;

static void ui_put_char(uint8_t x, uint8_t y, char ch);
static void ui_draw_num2(uint8_t x, uint8_t y, uint8_t val);

static font_t ibm_font;

/* First VRAM tile the console font occupies.  font_t is a *handle* (a RAM
 * pointer to a {first_tile, font_ptr} entry, value 0xCD74), not a tile
 * base: using it directly (ibm_font + ch) renders tiles at 0x74+ch, i.e.
 * unloaded VRAM.  Cached from the handle at ui_init; the IBM font's
 * first_tile is 0.
 *
 * The console font packs its glyphs starting at space (0x20), so the tile
 * for char `ch` is base + (ch - ' ') -- never base + ch, which renders the
 * glyph for (ch + 0x20) instead.  Every tilemap write below applies that
 * offset. */
static uint8_t ui_font_tile_base;

static const palette_color_t cgb_palette[4] = {
    RGB8(255, 255, 255),
    RGB8(170, 170, 170),
    RGB8(85, 85, 85),
    RGB8(0, 0, 0)
};

/* Player-sprite ramp: entry 3 (the hero ink color) is light grey so the
 * hero is visible against the white floor on CGB. */
static const palette_color_t cgb_sprite_palette[4] = {
    RGB8(255, 255, 255),
    RGB8(255, 255, 255),
    RGB8(255, 255, 255),
    RGB8(170, 170, 170)
};

/* ── Player sprite ─────────────────────────────────────────────────
 * Tile data is generated by tools/png2gb.py from assets/player_demo.png
 * (make gfx); see docs/graphics.md.  The array is included verbatim. */
#include "gfx/player_sprite_tile.h"
#include "gfx/rpg_tile_lookup.h"
#include "banked.h"

#define PLAYER_SPRITE_NUM 0
#define PLAYER_SPRITE_TILE_ID 102

/* ASCII semantic char per TileType (0..3): '.', '#', '>', 'B'.  The
 * overworld renders these via the console font (ui_font_tile_base + (ch -
 * ' ')); this branch is ASCII-only -- real terrain tiles live on the gfx
 * branch. */
static const char g_sem_map[8] = { '.', '#', '>', 'B', '1', '2', '3', '4' };

void ui_init(void)
{
    /* Turn the LCD off before loading the font so that display_off() inside
     * set_bkg_data() returns immediately (it waits for VBlank otherwise).
     * The CRT0 boot already leaves the LCD off; the harness (which skips
     * CRT0) needs this too, and mGBA's debugger does not advance VBlank
     * during single-stepping. */
    LCDC_REG &= ~0x80;

    oam_dma_init();
    font_init();
    ibm_font = font_load(font_ibm);
    font_set(ibm_font);
    ui_font_tile_base = ((pmfont_handle)ibm_font)->first_tile;

    /* Load world background tiles from Bank 2 (16 tiles = 256 bytes) using g_ui_screen_buf as temporary buffer */
    banked_copy(2, g_ui_screen_buf, g_rpg_world_tiles, 128);
    banked_copy(2, (uint8_t *)g_ui_screen_buf + 128, g_rpg_world_tiles + 128, 128);
    set_bkg_data(RPG_TILE_BASE_EXTERIOR, 16, (const uint8_t *)g_ui_screen_buf);

    /* Disable GBDK console auto-scroll.  When putchar() advances the cursor
     * past the bottom-right tile, the console normally scrolls the whole
     * screen up one line.  M_NO_SCROLL (bit 2 of the console .mode byte,
     * exposed as console_mode by crt0.s) makes it reset the cursor instead. */
    console_mode |= M_NO_SCROLL;

    /* Set DMG palettes: 0xE4 = 11 10 01 00 (Lightest to Darkest) */
    BGP_REG = 0xE4;
    OBP0_REG = 0xE4;
    OBP1_REG = 0xE4;

    /* Set CGB Palettes 0-7 if running on CGB hardware */
    if (_cpu == CGB_TYPE) {
        uint8_t p;
        BCPS_REG = 0x80;
        for (p = 0; p < 64; p++) {
            BCPD_REG = ((const uint8_t *)cgb_palette)[p & 7];
        }
        OCPS_REG = 0x80;
        for (p = 0; p < 64; p++) {
            OCPD_REG = ((const uint8_t *)cgb_sprite_palette)[p & 7];
        }
    }

    SHOW_BKG;

    /* HUD window layer: the window uses tilemap 0x9C00 (LCDC bit 6) so the
     * SCX/SCY-scrolled BG map (0x9800) is separate from the fixed HUD.
     * WX=7 puts the window at the display left edge; the window stays
     * disabled until ui_hud_show() (overworld) enables it, and
     * ui_hud_hide() disables it on every other screen. */
    LCDC_REG |= 0x40;   /* window tilemap base 0x9C00 */
    WX_REG = 7;
    WY_REG = 96;

    ui_sprite_init();
    DISPLAY_ON;
}

/* Show the HUD window at the bottom of the display (the overworld only).
 * The window is always enabled while the HUD is visible; its tilemap
 * (0x9C00) holds the HUD. */
void ui_hud_show(void)
{
    SHOW_WIN;
    WY_REG = 96;
}

/* Hide the HUD window (every screen but the overworld). */
void ui_hud_hide(void)
{
    HIDE_WIN;
}

/* Load the player sprite tile and enable the OAM sprite.  Called from
 * ui_init() while the LCD is still off: set_sprite_data() writes VRAM
 * through the same path as set_bkg_data() (both live in set_data.o) and
 * returns immediately while the LCD is off, so this stays harness-safe
 * (AGENTS.md 52.6).  The sprite starts hidden (OAM Y = 0); the overworld
 * render positions it via ui_sprite_move(). */
void ui_sprite_init(void)
{
    uint16_t i;
    for (i = 0; i < (96 * 16); i++) {
        ((volatile uint8_t *)0x8000)[i] = ((volatile uint8_t *)0x9000)[i];
    }
    for (i = 0; i < 16; i++) {
        ((volatile uint8_t *)0x8000)[PLAYER_SPRITE_TILE_ID * 16 + i] = player_sprite_tile[i];
    }
    set_sprite_tile(PLAYER_SPRITE_NUM, PLAYER_SPRITE_TILE_ID);
    SPRITES_8x8;
    SHOW_SPRITES;
    hide_sprite(PLAYER_SPRITE_NUM);
}

/* Position the player sprite at pixel coordinate (px, py), where a tile at
 * (tx, ty) is at (tx*8, ty*8).  Hardware OAM coordinates are offset +8/+16
 * from the visible pixel grid (GBDK's move_sprite takes raw OAM
 * coordinates, not screen tiles); a valid position (y >= 16) also un-hides
 * the sprite.  Only shadow OAM is written here; ui_sprite_commit() (called
 * once at the end of every frame) DMAs it to real OAM at the frame boundary,
 * so the displayed sprite is always in the correct state for the current
 * screen. */
void ui_sprite_move(uint8_t px, uint8_t py)
{
    move_sprite(PLAYER_SPRITE_NUM, (uint8_t)(px + 8), (uint8_t)(py + 16));
}

/* Hide the player sprite (OAM Y = 0).  Called on transitions away from the
 * overworld so the blob does not float over battle/menu screens.  The sprite
 * is also hidden in real OAM immediately (see ui_sprite_begin_transition)
 * so it is gone before the new screen's full redraw starts wiping the
 * display. */
void ui_sprite_hide(void)
{
    uint8_t i;
    for (i = 0; i <= MAX_WORLD_ACTORS; i++) {
        hide_sprite(i);
    }
    ui_sprite_begin_transition();
}

/* Hide the player and actor sprites in real OAM right now, before the new
 * screen's full redraw runs. */
void ui_sprite_begin_transition(void)
{
    uint8_t i;
    for (i = 0; i <= MAX_WORLD_ACTORS; i++) {
        shadow_OAM[i].y = 0;
    }
    refresh_OAM();
}

/* DMA shadow OAM to real OAM.  Called once per frame from main.c right after
 * vsync (during VBlank) so every displayed frame has the sprite in the
 * correct state for that frame; transitions force the hide beforehand in
 * ui_sprite_begin_transition(). */
void ui_sprite_commit(void)
{
    refresh_OAM();
}

void ui_lcd_off(void)
{
    LCDC_REG &= ~0x80;
}

void ui_lcd_on(void)
{
    LCDC_REG |= 0x80;
}

void ui_clear_screen(void)
{
    uint8_t x, y;
    /* Always select VRAM bank 0 before tilemap writes: on CGB, VBK_REG = 1
     * selects the CGB attribute bank and writes land there instead of the
     * tile-index bank.  Written directly -- not through gotoxy/putchar --
     * so full-screen clears are a tight VRAM loop that fits in VBlank. */
    VBK_REG = 0;
    for (y = 0; y < 18; y++) {
        for (x = 0; x < 20; x++) {
            ((volatile uint8_t *)0x9800)[y * 32 + x] =
                ui_font_tile_base;
            g_ui_screen_buf[y][x] = ' ';
        }
        g_ui_screen_buf[y][20] = '\0';
    }
}

static void ui_draw_text_line_ring(uint8_t x, uint8_t y, const char *text,
                                   uint8_t max_chars, uint8_t ox, uint8_t oy)
{
    uint8_t i = 0;
    uint8_t ended;
    char ch;
    if (y >= 18) return;
    VBK_REG = 0;  /* tile-index bank, not the CGB attribute bank */
    ended = (text == NULL);
    while (i < max_chars) {
        if (!ended && text[i] == '\0') ended = 1;
        ch = ended ? ' ' : text[i];
        if ((x + i) < 20) {
            ((volatile uint8_t *)0x9800)[((y + oy) & 31) * 32 + ((x + ox + i) & 31)] =
                (uint8_t)(ui_font_tile_base + (uint8_t)(ch - ' '));
            g_ui_screen_buf[y][x + i] = ch;
        }
        i++;
    }
}

void ui_draw_text_line(uint8_t x, uint8_t y, const char *text, uint8_t max_chars)
{
    ui_draw_text_line_ring(x, y, text, max_chars, 0, 0);
}

/* Camera-offset variants of ui_put_char/ui_draw_text_line for the dialogue
 * box, which overlays the frozen (SCX/SCY-scrolled) overworld: the screen
 * anchor is the modal rows 12-17, but the ring must hold them at
 * ((y+scroll)&31) so the PPU, which reads ring row (scroll + R) & 31 at
 * screen row R, actually displays the box where it should be.  g_ui_screen_buf
 * stays screen-anchored, so the harness semantic rows are unchanged.  Safe
 * for every current map (18 rows -> scroll_y <= 6 -> box rows <= 23; FIELD
 * scroll_x <= 12 -> box cols <= 31), so the & 31 wrap is belt-and-braces. */
static void ui_put_char_ring(uint8_t x, uint8_t y, char ch, uint8_t ox, uint8_t oy)
{
    if (y < 18 && x < 20) {
        VBK_REG = 0;  /* tile-index bank, not the CGB attribute bank */
        ((volatile uint8_t *)0x9800)[((y + oy) & 31) * 32 + ((x + ox) & 31)] =
            (uint8_t)(ui_font_tile_base + (uint8_t)(ch - ' '));
        g_ui_screen_buf[y][x] = ch;
    }
}

static const uint16_t s_powers10[5] = { 10000, 1000, 100, 10, 1 };

void ui_format_int(int16_t value, char *out)
{
    uint16_t uval;
    uint8_t i, digit, started = 0;
    uint8_t j = 0;

    if (!out) return;
    if (value < 0) {
        out[j++] = '-';
        uval = (uint16_t)(-value);
    } else {
        uval = (uint16_t)value;
    }

    for (i = 0; i < 5; i++) {
        digit = 0;
        while (uval >= s_powers10[i]) {
            uval -= s_powers10[i];
            digit++;
        }
        if (digit > 0 || started || i == 4) {
            out[j++] = (char)('0' + digit);
            started = 1;
        }
    }
    out[j] = '\0';
}

/* One world cell into the 32x32 background tilemap ring at the wrapped
 * address (the PPU reads the background at SCX/SCY = the absolute camera
 * pixel position, so the ring must hold the world tiles at (world & 31)).
 * An actor's font char overlays its terrain tile; both stay in the ring so
 * the cell is correct whenever it scrolls back into view.  The screen-
 * anchored semantic g_ui_screen_buf (harness get_screen_buf) is filled for
 * visible cells.  Written directly -- not through set_bkg_tiles -- to avoid
 * pulling the GBDK .set_xy_* helpers into the non-bankable _HOME area. */
static void ui_draw_world_cell_ex(const World *world, uint8_t col, uint8_t row)
{
    uint8_t t;
    uint8_t tile_idx;
    uint8_t sx;
    uint8_t sy;
    const WorldActorDefinition *actor;
    volatile uint8_t *tilemap = (volatile uint8_t *)0x9800;

    if (col >= world->width || row >= world->height) {
        t = TILE_FLOOR;
    } else {
        t = world->map[row][col];
    }

    actor = actor_find_at(world, col, row);
    if (actor && !(actor->flags & ACTOR_FLAG_HOSTILE)) {
        tile_idx = (uint8_t)(ui_font_tile_base + (uint8_t)(actor->visual - ' '));
    } else {
        uint8_t lookup_id = rpg_lookup_tile_id(scene_get_tileset(world->map_id), g_sem_map[t]);
        if (lookup_id) {
            tile_idx = lookup_id;
        } else {
            tile_idx = (uint8_t)(ui_font_tile_base + (uint8_t)(g_sem_map[t] - ' '));
        }
    }
    tilemap[(row & 31) * 32 + (col & 31)] = tile_idx;
#ifdef DEBUG_BUILD
    g_tilemap_mirror[(row & 31) * 32 + (col & 31)] = tile_idx;
#endif

    sx = (uint8_t)(col - world->scroll_x);
    sy = (uint8_t)(row - world->scroll_y);
    if (sx < WORLD_VIEW_W && sy < WORLD_VIEW_H) {
        g_ui_screen_buf[sy][sx] = (actor && !(actor->flags & ACTOR_FLAG_HOSTILE)) ? actor->visual : g_sem_map[t];
    }
}

static void ui_draw_world_cell(const World *world, uint8_t col, uint8_t row)
{
    ui_draw_world_cell_ex(world, col, row);
}

void ui_draw_actors_sprites(const World *world)
{
    uint8_t slot;
    const WorldActorRuntime *a;
    uint8_t px, py;
    uint8_t spr_num;

    if (!world) return;

    for (slot = 0; slot < MAX_WORLD_ACTORS; slot++) {
        a = &world->actors[slot];
        spr_num = (uint8_t)(1 + slot);
        if (!a->active) {
            hide_sprite(spr_num);
            continue;
        }
        px = (uint8_t)(world_actor_px(a) - world->camera_px_x);
        py = (uint8_t)(world_actor_py(a) - world->camera_px_y);

        if (px < 160 && py < 96) {
            move_sprite(spr_num, (uint8_t)(px + 8), (uint8_t)(py + 16));
            set_sprite_tile(spr_num, (uint8_t)(ui_font_tile_base + (uint8_t)(a->visual - ' ')));
        } else {
            hide_sprite(spr_num);
        }
    }
}

/* Draw every cell in [c0,c1) x [r0,r1) into the tilemap ring. */
static void ui_draw_world_rect(const World *world, uint8_t c0, uint8_t c1,
                               uint8_t r0, uint8_t r1)
{
    uint8_t col, row;
    VBK_REG = 0;   /* the tilemap ring lives in VRAM bank 0 */
    for (row = r0; row < r1; row++) {
        for (col = c0; col < c1; col++) {
            ui_draw_world_cell(world, col, row);
        }
    }
}

/* Refill the semantic view from the tilemap ring mirror (DEBUG-only).  The
 * ring/mirror is the ground truth of what is rendered; every cell is an
 * ASCII console-font tile (terrain and actors both draw via the font), so
 * decoding back to a char is base + tile_index - ui_font_tile_base. */
#ifdef DEBUG_BUILD
static void ui_refill_semantic(const World *world)
{
    uint8_t x, y, col, row, slot;
    const WorldActorRuntime *a;
    uint8_t sx, sy;

    for (y = 0; y < WORLD_VIEW_H; y++) {
        for (x = 0; x < WORLD_VIEW_W; x++) {
            col = (uint8_t)(world->scroll_x + x);
            row = (uint8_t)(world->scroll_y + y);
            if (col >= world->width || row >= world->height) {
                g_ui_screen_buf[y][x] = '.';
            } else {
                g_ui_screen_buf[y][x] = g_sem_map[world->map[row][col]];
            }
        }
    }

    for (slot = 0; slot < MAX_WORLD_ACTORS; slot++) {
        a = &world->actors[slot];
        if (!a->active) continue;
        sx = (uint8_t)(a->x - world->scroll_x);
        sy = (uint8_t)(a->y - world->scroll_y);
        if (sx < WORLD_VIEW_W && sy < WORLD_VIEW_H) {
            g_ui_screen_buf[sy][sx] = (char)a->visual;
        }
    }
}
#endif

void ui_draw_world_map(const World *world)
{
    uint8_t y;
    if (!world) return;

    /* Populate the entire 32-column x 18-row background ring during LCD-safe
     * full map redraw. Field: all 32 x 18 cells. Smaller maps: col 20..31 are
     * filled with floor tiles in ui_draw_world_cell. */
    ui_draw_world_rect(world, 0, 32, 0, 18);
    for (y = 0; y < WORLD_VIEW_H; y++) {
        g_ui_screen_buf[y][WORLD_VIEW_W] = '\0';
    }

#ifdef DEBUG_BUILD
    ui_refill_semantic(world);
#endif

    /* The ASCII @ is an OAM glyph, not a BG tile. */
    ui_sprite_move((uint8_t)(world_player_px(world) - world->camera_px_x),
                   (uint8_t)(world_player_py(world) - world->camera_px_y));
    ui_draw_actors_sprites(world);
}

void ui_update_camera(const World *world)
{
    if (!world) return;
    SCX_REG = world->camera_px_x;
    SCY_REG = world->camera_px_y;
#ifdef DEBUG_BUILD
    ui_refill_semantic(world);
#endif
}

/* Write one char to the HUD window tilemap (0x9C00) row `y` (0-5, displayed
 * at screen rows 12-17) and mirror it into the semantic g_ui_screen_buf.
 * The console font packs its glyphs starting at space, so char `ch` is tile
 * base + (ch - ' ').  Callers pass in-range coordinates (x < 20, y < 6). */
static void ui_hud_put_char(uint8_t x, uint8_t y, char ch)
{
    ((volatile uint8_t *)0x9C00)[y * 32 + x] = (uint8_t)(ui_font_tile_base + (uint8_t)(ch - ' '));
    g_ui_screen_buf[12 + y][x] = ch;
}

static void ui_hud_text_line(uint8_t y, const char *text, uint8_t max_chars)
{
    uint8_t i = 0;
    char ch;
    while (text && text[i] != '\0' && i < max_chars) {
        ch = text[i];
        ui_hud_put_char(i, y, ch);
        i++;
    }
    while (i < max_chars) {
        ui_hud_put_char(i, y, ' ');
        i++;
    }
}

static void ui_hud_num2(uint8_t x, uint8_t y, uint8_t val)
{
    uint8_t d = 0;
    while (val >= 10) {
        val -= 10;
        d++;
    }
    ui_hud_put_char(x, y, d ? (char)('0' + d) : ' ');
    ui_hud_put_char(x + 1, y, (char)('0' + val));
}

void ui_draw_overworld_hud(const World *world)
{
    const char *label;
    uint8_t r;

    if (!world) return;

    /* The HUD lives in the WINDOW layer (0x9C00, VRAM bank 0).  Force the
     * VRAM bank select to 0 first so the tilemap writes land in bank 0 (not
     * the CGB attribute bank). */
    VBK_REG = 0;

    switch (world->map_id) {
        case MAP_TOWN:          label = "MAP: TOWN | HP:";  break;
        case MAP_FOREST:        label = "MAP: FORST| HP:";  break;
        case MAP_MOUNTAIN_PASS: label = "MAP: MOUNT| HP:";  break;
        case MAP_CASTLE:        label = "MAP: CASTL| HP:";  break;
        default:                label = "MAP: FIELD| HP:";  break;
    }

    /* The HUD lives in the WINDOW layer (0x9C00), so the SCX/SCY-scrolled
     * background map never carries it.  Window row y -> screen row 12+y. */
    ui_hud_text_line(0, "====================", 20);
    ui_hud_text_line(1, label, 15);
    ui_hud_num2(15, 1, world->player.hp);
    ui_hud_put_char(17, 1, '/');
    ui_hud_num2(18, 1, world->player.max_hp);
    for (r = 2; r <= 4; r++) ui_hud_text_line(r, "", 20);
    ui_hud_text_line(5, " [D-PAD] MOVE HERO", 20);
}

void ui_draw_world_full(const World *world)
{
    if (!world) return;
    ui_clear_screen();
    ui_draw_world_map(world);
    ui_draw_overworld_hud(world);
    ui_hud_show();
}

static void ui_put_char(uint8_t x, uint8_t y, char ch)
{
    if (y < 18 && x < 20) {
        VBK_REG = 0;  /* tile-index bank, not the CGB attribute bank */
        ((volatile uint8_t *)0x9800)[y * 32 + x] =
            (uint8_t)(ui_font_tile_base + (uint8_t)(ch - ' '));
        g_ui_screen_buf[y][x] = ch;
    }
}

static void ui_draw_num2(uint8_t x, uint8_t y, uint8_t val)
{
    uint8_t d = 0;
    while (val >= 10) {
        val -= 10;
        d++;
    }
    ui_put_char(x, y, d ? (char)('0' + d) : ' ');
    ui_put_char(x + 1, y, (char)('0' + val));
}

/* Draw a battle HP line: "  HP: <hp>/<max>" at row y. */
static void ui_draw_hp_row(uint8_t y, uint8_t hp, uint8_t max_hp)
{
    ui_draw_text_line(0, y, "  HP: ", 6);
    ui_draw_num2(6, y, hp);
    ui_put_char(8, y, '/');
    ui_draw_num2(9, y, max_hp);
}

void ui_draw_battle_full(const Battle *battle)
{
    if (!battle) return;

    ui_clear_screen();

    ui_draw_text_line(0, 0, "====================", 20);
    ui_draw_text_line(0, 1, "    BATTLE ENCOUNTER", 20);
    ui_draw_text_line(0, 2, "====================", 20);

    ui_draw_text_line(0, 5, "  ENEMY: ", 9);
    ui_draw_text_line(9, 5, battle->enemy.name ? battle->enemy.name : "ENEMY", 8);
    ui_draw_hp_row(6, battle->enemy.hp, battle->enemy.max_hp);

    ui_draw_text_line(0, 9, "  HERO:", 7);
    ui_draw_hp_row(10, battle->player.hp, battle->player.max_hp);

    ui_draw_text_line(0, 13, "--------------------", 20);

    ui_update_battle(battle);

    /* Show the real hero sprite next to the "HERO:" label (text row 9,
     * col 15 -- where the old ASCII '@' sat), un-hiding it from the
     * screen_change() hide on the way in.  Only shadow OAM is written here;
     * the frame-boundary commit (ui_sprite_commit after vsync) DMAs it to
     * real OAM, so the sprite appears once the battle screen is drawn. */
    move_sprite(PLAYER_SPRITE_NUM, 128, 88);
}

void ui_update_battle(const Battle *battle)
{
    const char *msg;
    if (!battle) return;

    /* Keep HP readouts current as damage is dealt/received */
    ui_draw_hp_row(6, battle->enemy.hp, battle->enemy.max_hp);
    ui_draw_hp_row(10, battle->player.hp, battle->player.max_hp);

    if (battle->result == BATTLE_RESULT_VICTORY) {
        msg = " VICTORY! PRESS [A]";
    } else if (battle->result == BATTLE_RESULT_DEFEAT) {
        msg = " DEFEATED! PRESS [A]";
    } else if (battle->result == BATTLE_RESULT_FLED) {
        msg = " FLED! PRESS [A]";
    } else if (battle->turn == BATTLE_TURN_PLAYER) {
        msg = " [A] ATTACK  [B] RUN";
    } else {
        msg = " ENEMY TURN...";
    }
    ui_draw_text_line(0, 15, msg, 20);
}

void ui_draw_dialogue(const DialogueState *dialogue, uint8_t scroll_x, uint8_t scroll_y)
{
    uint8_t y;
    if (!dialogue || !dialogue->active) return;
    if (dialogue->current_line >= dialogue->line_count) return;

    /* Dialogue box occupies dedicated modal overlay region: rows 12-17 (6 rows, 20 columns) */
    ui_draw_text_line_ring(0, 12, "+------------------+", 20, scroll_x, scroll_y);
    for (y = 13; y <= 16; y++) {
        ui_put_char_ring(0, y, '|', scroll_x, scroll_y);
        ui_put_char_ring(19, y, '|', scroll_x, scroll_y);
    }
    ui_draw_text_line_ring(1, 13, dialogue->speaker ? dialogue->speaker : "", 18, scroll_x, scroll_y);
    ui_draw_text_line_ring(1, 14, dialogue->lines[dialogue->current_line], 18, scroll_x, scroll_y);
    ui_draw_text_line_ring(1, 15, "", 18, scroll_x, scroll_y);
    ui_draw_text_line_ring(1, 16, " [A] CONTINUE", 18, scroll_x, scroll_y);
    ui_draw_text_line_ring(0, 17, "+------------------+", 20, scroll_x, scroll_y);
}

void ui_draw_game_over(uint8_t choice)
{
    ui_clear_screen();
    ui_draw_text_line(4, 3, "GAME OVER", 9);
    ui_draw_text_line(3, 8, "CONTINUE?", 9);
    ui_draw_text_line(0, 11, choice ? "  YES" : "> YES", 5);
    ui_draw_text_line(0, 12, choice ? "> NO" : "  NO", 4);
    ui_draw_text_line(1, 16, "[A] CONFIRM", 11);
}

void ui_draw_thanks(void)
{
    ui_clear_screen();
    ui_draw_text_line(1, 8, "THANKS FOR PLAYING!", 19);
}

#ifdef DEBUG_BUILD
void ui_draw_font_test(void)
{
    uint8_t ch, row = 0, col = 0;
    ui_clear_screen();
    for (ch = ' '; ch <= '~'; ch++) {
        ((volatile uint8_t *)0x9800)[row * 32 + col] = (uint8_t)(ui_font_tile_base + (uint8_t)(ch - ' '));
        g_ui_screen_buf[row][col] = (char)ch;
        col++;
        if (col == 20) {
            col = 0;
            row += 2;
        }
    }
}
#endif
