#include "ui.h"
#include "actor.h"
#include "scene.h"
#include <gb/gb.h>
#include <gb/cgb.h>
#include <gbdk/font.h>
#include <gbdk/console.h>
#include <stdio.h>

char g_ui_screen_buf[18][21];

#ifdef DEBUG_BUILD
/* Mirror of the background tilemap ring (0x9800), written alongside every
 * ring write, so the harness can assert the actual rendered map (mGBA's
 * debugger cannot read VRAM).  DEBUG-only: 1 KB of WRAM the release does
 * not carry. */
uint8_t g_tilemap_mirror[32 * 32];

/* Mirror of the HUD window tilemap (0x9C00 rows 0-5), written alongside
 * every ui_hud_put_char write.  The window tilemap lives in VRAM, whose
 * reads/writes are unreliable under the harness (scanout drops) and in
 * mGBA's debugger, so the font-mapping regression check reads this WRAM
 * mirror instead (it captures the ROM's write *intent*).  DEBUG-only. */
uint8_t g_hud_tilemap_mirror[6 * 32];
#endif

/* GBDK console .mode byte (defined in crt0.s _DATA). Bit 2 is M_NO_SCROLL. */
extern uint8_t console_mode;

static void ui_put_char(uint8_t x, uint8_t y, char ch);
static void ui_draw_num2(uint8_t x, uint8_t y, uint8_t val);

static font_t ibm_font;

/* Real first tile of the loaded console font.  ibm_font is a GBDK font
 * *handle* (a RAM pointer to a {first_tile, font_ptr} entry, value 0xCD74),
 * not a tile base: using it directly (ibm_font + ch) renders tiles at
 * 0x74+ch, i.e. unloaded VRAM.  Cached from the handle at ui_init; the IBM
 * font's first_tile is 0.
 *
 * The console font packs its glyphs starting at space (0x20), so the tile
 * for char `ch` is base + (ch - ' ') -- never base + ch, which renders the
 * glyph for (ch + 0x20) instead.  Every tilemap write below applies that
 * offset. */
static uint8_t ui_font_tile_base;

static const palette_color_t cgb_palette[4] = {
    RGB8(255, 255, 255),
    RGB8(170, 170, 170),
    RGB8(85, 85, 85),
    RGB8(0, 0, 0)
};

/* ── Player sprite ─────────────────────────────────────────────────
 * Tile data is generated by tools/png2gb.py from assets/player_demo.png
 * (make gfx); see docs/graphics.md.  The array is included verbatim. */
#include "gfx/player_sprite_tile.h"

/* ── World terrain tileset ─────────────────────────────────────────
 * Generated by tools/png2gb.py from assets/world_tiles.png (make gfx);
 * tile 0 = FLOOR, 1 = WALL, 2 = BUILDING, 3 = EXIT.  Loaded into VRAM at
 * WORLD_TILE_BASE (>= 128) so it never collides with the GBDK console
 * font tiles (0..127) or the OAM sprite tile.  The overworld draws these
 * into the background tilemap (rows 0..WORLD_VIEW_H-1); dialogue/battle/
 * menus keep the console font. */
#include "gfx/world_tiles.h"

#define WORLD_TILE_BASE     128
#define WORLD_TILE_FLOOR    0
#define WORLD_TILE_WALL     1
#define WORLD_TILE_BUILDING 2
#define WORLD_TILE_EXIT     3

#define PLAYER_SPRITE_NUM 0
#define PLAYER_SPRITE_TILE_ID 102

/* Map TileType (0..3) -> tileset tile index and ASCII semantic char. */
static const uint8_t g_tile_map[4] = {
    WORLD_TILE_FLOOR, WORLD_TILE_WALL, WORLD_TILE_EXIT, WORLD_TILE_BUILDING
};
static const char g_sem_map[4] = { '.', '#', '>', 'B' };

/* ── Real tilesets (battle background, window frame, enemy sprites) ──
 * The tile/map BYTES are game content in banked ROM (src/game/gfx_content.c,
 * GAME_CONTENT_BANK, generated by make gfx with --global).  ui_gfx_load()
 * copies each into VRAM via banked_copy() once, after banked_copy_init()
 * (game_init); renderers then read only VRAM, never banked ROM. */
#include "banked.h"
#include "game_ids.h"

extern const uint8_t battle_bg_tiles[];
extern const uint8_t battle_bg_map[2][4];
extern const uint8_t ui_frame_tiles[];
extern const uint8_t enemy_slime[];
extern const uint8_t enemy_bat[];
extern const uint8_t enemy_boss[];
extern const uint8_t npc_mayor[];
extern const uint8_t npc_guard[];
extern const uint8_t npc_shopkeeper[];
extern const uint8_t npc_merchant[];
extern const uint8_t npc_amulet[];

/* WRAM staging for the battle-background tilemap (renderers read this;
 * banked data is copied out once at boot). */
static uint8_t g_battle_bg_map[2][4];

/* Copy one banked tileset's `n` tile bytes into VRAM at tile base `base`. */
static void ui_gfx_load_tiles(uint8_t base, const uint8_t *tiles, uint8_t n)
{
    volatile uint8_t *vram = (volatile uint8_t *)(0x8000 + (uint16_t)base * 16);
    VBK_REG = 0;
    banked_copy(GAME_CONTENT_BANK, (void *)vram, tiles, (uint8_t)(n * 16));
}

/* Copy all registered tilesets into VRAM.  Called once from game_init right
 * after banked_copy_init() (which the harness also runs), so the trampoline
 * is resident in both real and harness boots. */
void ui_gfx_load(void)
{
    ui_gfx_load_tiles(UI_BATTLE_BG_TILE_BASE, battle_bg_tiles, 3);
    ui_gfx_load_tiles(UI_FRAME_TILE_BASE, ui_frame_tiles, 9);
    ui_gfx_load_tiles(UI_ENEMY_SLIME_TILE, enemy_slime, 1);
    ui_gfx_load_tiles(UI_ENEMY_BAT_TILE, enemy_bat, 1);
    ui_gfx_load_tiles(UI_ENEMY_BOSS_TILE_BASE, enemy_boss, 4);
    ui_gfx_load_tiles((uint8_t)(UI_NPC_TILE_BASE + 0), npc_mayor, 1);
    ui_gfx_load_tiles((uint8_t)(UI_NPC_TILE_BASE + 1), npc_guard, 1);
    ui_gfx_load_tiles((uint8_t)(UI_NPC_TILE_BASE + 2), npc_shopkeeper, 1);
    ui_gfx_load_tiles((uint8_t)(UI_NPC_TILE_BASE + 3), npc_merchant, 1);
    ui_gfx_load_tiles((uint8_t)(UI_NPC_TILE_BASE + 4), npc_amulet, 1);
    VBK_REG = 0;
    banked_copy(GAME_CONTENT_BANK, g_battle_bg_map, (const void *)battle_bg_map, 8);
}

/* The staged battle-background tilemap (4x2). */
const uint8_t *ui_gfx_map(void)
{
    return (const uint8_t *)g_battle_bg_map;
}

/* Copy `n` bytes of static tile data into VRAM at the tile-id base `base`
 * (LCD must be off or the writes land mid-frame; ui_init calls this while
 * the LCD is off).  Forces VBK_REG to 0 so data lands in VRAM bank 0, not
 * the CGB attribute bank. */
static void ui_load_tiles_to_vram(uint8_t base, const uint8_t *tiles, uint16_t n)
{
    volatile uint8_t *vram = (volatile uint8_t *)(0x8000 + (uint16_t)base * 16);
    uint16_t i;
    VBK_REG = 0;
    for (i = 0; i < n; i++) {
        vram[i] = tiles[i];
    }
}

void ui_init(void)
{
    /* Turn the LCD off before loading the font so that display_off() inside
     * set_bkg_data() returns immediately (it waits for VBlank otherwise).
     * The CRT0 boot already leaves the LCD off; the harness (which skips
     * CRT0) needs this too, and mGBA's debugger does not advance VBlank
     * during single-stepping. */
    LCDC_REG &= ~0x80;

    font_init();
    ibm_font = font_load(font_ibm);
    font_set(ibm_font);
    ui_font_tile_base = ((pmfont_handle)ibm_font)->first_tile;

    /* Load the overworld terrain tileset into VRAM at WORLD_TILE_BASE.
     * Written directly (not via set_bkg_data) because set_bkg_data toggles
     * the LCD off/on internally, which under the release boot turns the LCD
     * on mid-init and can leave the display blank.  The LCD is still off
     * here, so the writes are safe and harness-compatible. */
    ui_load_tiles_to_vram(WORLD_TILE_BASE, world_tiles, sizeof(world_tiles));

    /* The battle bg / frame / enemy tilesets are banked content loaded by
     * ui_gfx_load() from game_init (banked_copy_init runs there). */

    /* Disable GBDK console auto-scroll.  When putchar() advances the cursor
     * past the bottom-right tile, the console normally scrolls the whole
     * screen up one line.  M_NO_SCROLL (bit 2 of the console .mode byte,
     * exposed as console_mode by crt0.s) makes it reset the cursor instead. */
    console_mode |= M_NO_SCROLL;

    /* Set DMG palettes: 0xE4 = 11 10 01 00 (Lightest to Darkest) */
    BGP_REG = 0xE4;
    OBP0_REG = 0xE4;
    OBP1_REG = 0xE4;

    /* Set CGB Palette 0 if running on CGB hardware */
    if (_cpu == CGB_TYPE) {
        set_bkg_palette(0, 1, cgb_palette);
    }

    SHOW_BKG;

    /* HUD window layer: the window uses tilemap 0x9C00 (LCDC bit 6) so the
     * SCX/SCY-scrolled BG map (0x9800) is separate from the fixed HUD.
     * WX=7 puts the window at the display left edge; the window stays
     * disabled until ui_hud_show() (overworld) enables it, and
     * ui_hud_hide() disables it on every other screen. */
    LCDC_REG |= 0x40;   /* window tilemap base 0x9C00 */
    WX_REG = 7;
    WY_REG = 96;

    ui_sprite_init();
    DISPLAY_ON;
}

/* Show the HUD window at the bottom of the display (the overworld only).
 * The window is always enabled while the HUD is visible; its tilemap
 * (0x9C00) holds the HUD. */
void ui_hud_show(void)
{
    SHOW_WIN;
    WY_REG = 96;
}

/* Hide the HUD window (every screen but the overworld). */
void ui_hud_hide(void)
{
    HIDE_WIN;
}

/* Load the player sprite tile and enable the OAM sprite.  Called from
 * ui_init() while the LCD is still off: set_sprite_data() writes VRAM
 * through the same path as set_bkg_data() (both live in set_data.o) and
 * returns immediately while the LCD is off, so this stays harness-safe
 * (AGENTS.md 52.6).  The sprite starts hidden (OAM Y = 0); the overworld
 * render positions it via ui_sprite_move(). */
void ui_sprite_init(void)
{
    set_sprite_data(PLAYER_SPRITE_TILE_ID, 1, player_sprite_tile);
    set_sprite_tile(PLAYER_SPRITE_NUM, PLAYER_SPRITE_TILE_ID);
    SPRITES_8x8;
    SHOW_SPRITES;
    hide_sprite(PLAYER_SPRITE_NUM);
}

/* Position the player sprite at pixel coordinate (px, py), where a tile at
 * (tx, ty) is at (tx*8, ty*8).  Hardware OAM coordinates are offset +8/+16
 * from the visible pixel grid (GBDK's move_sprite takes raw OAM
 * coordinates, not screen tiles); a valid position (y >= 16) also un-hides
 * the sprite.  Only shadow OAM is written here; ui_sprite_commit() (called
 * once at the end of every frame) DMAs it to real OAM at the frame boundary,
 * so the displayed sprite is always in the correct state for the current
 * screen. */
void ui_sprite_move(uint8_t px, uint8_t py)
{
    move_sprite(PLAYER_SPRITE_NUM, (uint8_t)(px + 8), (uint8_t)(py + 16));
}

/* Enemy sprite OAM slots (the player owns slot 0; the battle enemy owns
 * slots 1..4 so the 16x16 boss can span a 2x2 grid). */
#define ENEMY_SPRITE_NUM 1

/* Show the battle enemy sprite at screen pixel (px, py) using the generic
 * enemy-gfx index (0=slime, 1=bat, 2=boss).  Only shadow OAM is written;
 * ui_sprite_commit() DMAs it to real OAM at the frame boundary. */
void ui_enemy_sprite_show(uint8_t gfx, uint8_t px, uint8_t py)
{
    uint8_t base = UI_ENEMY_SLIME_TILE;
    uint8_t i;

    if (gfx == 1) base = UI_ENEMY_BAT_TILE;
    else if (gfx == 2) base = UI_ENEMY_BOSS_TILE_BASE;

    /* Single 8x8 sprite for slime/bat; a 2x2 grid of four 8x8 sprites for
     * the 16x16 boss (tiles row-major: TL, TR, BL, BR). */
    move_sprite(ENEMY_SPRITE_NUM, (uint8_t)(px + 8), (uint8_t)(py + 16));
    set_sprite_tile(ENEMY_SPRITE_NUM, base);
    for (i = 0; i < 3; i++) {
        move_sprite((uint8_t)(ENEMY_SPRITE_NUM + 1 + i), 0, 0);
    }
    if (gfx == 2) {
        move_sprite((uint8_t)(ENEMY_SPRITE_NUM + 1), (uint8_t)(px + 8 + 8), (uint8_t)(py + 16));
        move_sprite((uint8_t)(ENEMY_SPRITE_NUM + 2), (uint8_t)(px + 8), (uint8_t)(py + 16 + 8));
        move_sprite((uint8_t)(ENEMY_SPRITE_NUM + 3), (uint8_t)(px + 8 + 8), (uint8_t)(py + 16 + 8));
        set_sprite_tile((uint8_t)(ENEMY_SPRITE_NUM + 1), (uint8_t)(base + 1));
        set_sprite_tile((uint8_t)(ENEMY_SPRITE_NUM + 2), (uint8_t)(base + 2));
        set_sprite_tile((uint8_t)(ENEMY_SPRITE_NUM + 3), (uint8_t)(base + 3));
    }
}

/* Hide the enemy sprite slots (OAM Y = 0).  Called alongside ui_sprite_hide
 * on transitions away from battle. */
void ui_enemy_sprite_hide(void)
{
    uint8_t i;
    for (i = 0; i < 4; i++) {
        hide_sprite((uint8_t)(ENEMY_SPRITE_NUM + i));
    }
}

/* Hide the player sprite (OAM Y = 0).  Called on transitions away from the
 * overworld so the blob does not float over battle/menu screens.  The sprite
 * is also hidden in real OAM immediately (see ui_sprite_begin_transition)
 * so it is gone before the new screen's full redraw starts wiping the
 * display. */
void ui_sprite_hide(void)
{
    hide_sprite(PLAYER_SPRITE_NUM);
    ui_enemy_sprite_hide();
    ui_sprite_begin_transition();
}

/* Hide the player sprite in real OAM right now, before the new screen's
 * full redraw runs.  The full redraw takes several display sweeps (the
 * screen blanks and redraws top-to-bottom); the hide must already be in real
 * OAM when it starts, or the sprite is shown at a stale position over the
 * wipe.  The intended final position is preserved in shadow OAM so the
 * frame-boundary commit reveals it on the new screen's first drawn frame. */
void ui_sprite_begin_transition(void)
{
    OAM_item_t *spr;
    uint8_t sy;

    spr = &shadow_OAM[PLAYER_SPRITE_NUM];
    sy = spr->y;
    spr->y = 0;                 /* hidden during the wipe */
    refresh_OAM();
    spr->y = sy;                /* keep the final position for the commit */
}

/* DMA shadow OAM to real OAM.  Called once per frame from main.c right after
 * vsync (during VBlank) so every displayed frame has the sprite in the
 * correct state for that frame; transitions force the hide beforehand in
 * ui_sprite_begin_transition(). */
void ui_sprite_commit(void)
{
    refresh_OAM();
}

void ui_clear_screen(void)
{
    uint8_t x, y;
    for (y = 0; y < 18; y++) {
        for (x = 0; x < 20; x++) {
            ((volatile uint8_t *)0x9C00)[y * 32 + x] =
                ui_font_tile_base;
            g_ui_screen_buf[y][x] = ' ';
        }
        g_ui_screen_buf[y][20] = '\0';
    }
}

void ui_draw_text_line(uint8_t x, uint8_t y, const char *text, uint8_t max_chars)
{
    uint8_t i = 0;
    char ch;
    if (y >= 18) return;
    while (i < max_chars) {
        ch = (text && text[i] != '\0') ? text[i] : ' ';
        if ((x + i) < 20) {
            ((volatile uint8_t *)0x9C00)[y * 32 + x + i] =
                (uint8_t)(ui_font_tile_base + (uint8_t)(ch - ' '));
            g_ui_screen_buf[y][x + i] = ch;
        }
        i++;
    }
}

void ui_format_int(int16_t value, char *out)
{
    char tmp[7];
    uint8_t i = 0;
    uint8_t j = 0;
    uint16_t mag;
    uint16_t digit;

    if (!out) return;
    /* Magnitude fits uint16 (int16 abs), avoiding the 32-bit div/mod
     * helpers SDCC would otherwise pull into the fixed bank. */
    mag = (value < 0) ? (uint16_t)(0 - (uint16_t)value) : (uint16_t)value;

    if (mag == 0) {
        tmp[i++] = '0';
    }
    while (mag > 0) {
        digit = (uint16_t)(mag % 10);
        tmp[i++] = (char)('0' + (uint8_t)digit);
        mag = (uint16_t)(mag / 10);
    }
    if (value < 0) {
        tmp[i++] = '-';
    }
    while (i > 0) {
        out[j++] = tmp[--i];
    }
    out[j] = '\0';
}

/* One world cell into the 32x32 background tilemap ring at the wrapped
 * address (the PPU reads the background at SCX/SCY = the absolute camera
 * pixel position, so the ring must hold the world tiles at (world & 31)).
 * A real-tile actor draws its tile id (and the sub-tiles of a multi-tile
 * footprint like the 2x2 boss); every other actor falls back to its ASCII
 * visual via the console font; terrain uses the overworld tileset.  All stay
 * in the ring so the cell is correct whenever it scrolls back into view.
 * The screen-anchored semantic g_ui_screen_buf (harness get_screen_buf) is
 * filled for visible cells with the actor's ASCII visual at its anchor cell
 * only -- a multi-tile footprint's cover cells show the terrain (actors are
 * single-cell entities).  Written directly -- not through set_bkg_tiles -- to
 * avoid pulling the GBDK .set_xy_* helpers into the non-bankable _HOME area. */
static void ui_draw_world_cell(const World *world, uint8_t col, uint8_t row)
{
    uint8_t t;
    uint8_t tile_idx;
    uint8_t sx;
    uint8_t sy;
    const WorldActorDefinition *foot;
    uint8_t ax;
    uint8_t ay;
    uint8_t sub;
    volatile uint8_t *tilemap = (volatile uint8_t *)0x9800;

    if (col >= world->width || row >= world->height) {
        t = TILE_FLOOR;
    } else {
        t = world->map[row][col];
    }

    foot = actor_find_footprint(world, col, row, &ax, &ay);
    if (foot && foot->tile_w != 0 && foot->tile_h != 0) {
        /* Multi-tile footprint (the 2x2 boss): the sub-tile is row-major,
         * anchor at (ax,ay).  tile_w is only ever 1 or 2, so the generic
         * multiply is avoided (a runtime multiply would pull the SDCC mul
         * helpers into the fixed bank). */
        sub = (uint8_t)(col - ax);
        if (foot->tile_w == 2) {
            sub += (uint8_t)((row - ay) << 1);
        } else {
            sub += (uint8_t)(row - ay);
        }
        tile_idx = (uint8_t)(foot->tile + sub);
    } else if (foot) {
        tile_idx = (uint8_t)(ui_font_tile_base + (uint8_t)(foot->visual - ' '));
    } else {
        tile_idx = (uint8_t)(WORLD_TILE_BASE + g_tile_map[t]);
    }
    tilemap[(row & 31) * 32 + (col & 31)] = tile_idx;
#ifdef DEBUG_BUILD
    g_tilemap_mirror[(row & 31) * 32 + (col & 31)] = tile_idx;
#endif

    sx = (uint8_t)(col - world->scroll_x);
    sy = (uint8_t)(row - world->scroll_y);
    if (sx < WORLD_VIEW_W && sy < WORLD_VIEW_H) {
        /* Semantic layer: a single-cell entity's visual at its anchor cell
         * only; a multi-tile footprint's cover cells show the terrain. */
        if (foot && ax == col && ay == row) {
            g_ui_screen_buf[sy][sx] = (char)foot->visual;
        } else {
            g_ui_screen_buf[sy][sx] = g_sem_map[t];
        }
    }
}

/* Draw every cell in [c0,c1) x [r0,r1) into the tilemap ring. */
static void ui_draw_world_rect(const World *world, uint8_t c0, uint8_t c1,
                               uint8_t r0, uint8_t r1)
{
    uint8_t col, row;
    VBK_REG = 0;   /* the tilemap ring lives in VRAM bank 0 */
    for (row = r0; row < r1; row++) {
        for (col = c0; col < c1; col++) {
            ui_draw_world_cell(world, col, row);
        }
    }
}

void ui_draw_world_map(const World *world)
{
    uint8_t y;
    if (!world) return;

    /* Full ring window around the camera: VIEW_W+1 columns x VIEW_H+1 rows
     * (the extra column/row covers the SCX/SCY sub-tile offset so no stale
     * tiles show at the display edges), then the semantic row terminators. */
    ui_draw_world_rect(world, world->scroll_x,
                       (uint8_t)(world->scroll_x + WORLD_VIEW_W + 1),
                       world->scroll_y,
                       (uint8_t)(world->scroll_y + WORLD_VIEW_H + 1));
    for (y = 0; y < WORLD_VIEW_H; y++) {
        g_ui_screen_buf[y][WORLD_VIEW_W] = '\0';
    }

    /* Sprite in camera-relative screen coordinates: the BG scrolls under
     * it via SCX/SCY, so the OAM position is (world px - camera px). */
    ui_sprite_move((uint8_t)(world_player_px(world) - world->camera_px_x),
                   (uint8_t)(world_player_py(world) - world->camera_px_y));
}

/* Refill the semantic view from the world (DEBUG-only).  The screen-anchored
 * buffer is decoded straight from the world + actors after the entering-edge
 * ring draw in ui_draw_world_scroll: world truth, and far cheaper in code
 * than decoding the ring mirror (the mirror stays assertable on its own via
 * tilemap_cell).  A multi-tile footprint's cover cells show the underlying
 * terrain -- actors are single-cell entities. */
#ifdef DEBUG_BUILD
static void ui_refill_semantic(const World *world)
{
    uint8_t x, y, col, row;
    const WorldActorDefinition *actor;

    for (y = 0; y < WORLD_VIEW_H; y++) {
        for (x = 0; x < WORLD_VIEW_W; x++) {
            col = (uint8_t)(world->scroll_x + x);
            row = (uint8_t)(world->scroll_y + y);
            actor = actor_find_at(world, col, row);
            g_ui_screen_buf[y][x] = actor ? (char)actor->visual
                                          : g_sem_map[world->map[row][col]];
        }
    }
}
#endif

/* Redraw when the camera crosses a tile boundary.  Incremental: only the
 * tilemap-ring column/row that entered the window is drawn (the ring holds
 * world tiles at wrapped (world & 31) addresses, so cells still in view are
 * already correct), then the semantic view is refilled from the mirror.
 * prev_sx/prev_sy are the previous scroll tile origin.  Falls back to a
 * full-window redraw on a diagonal or multi-tile scroll (debug teleports). */
void ui_draw_world_scroll(const World *world, uint8_t prev_sx, uint8_t prev_sy)
{
    int8_t dx, dy;
    uint8_t c0, c1, r0, r1;

    if (!world) return;
    dx = (int8_t)(world->scroll_x - prev_sx);
    dy = (int8_t)(world->scroll_y - prev_sy);
    if (dx == 0 && dy == 0) return;

    /* A diagonal or multi-tile scroll cannot be expressed as one entering
     * edge; redraw the window in full. */
    if ((dx != 0 && dy != 0) || dx < -1 || dx > 1 || dy < -1 || dy > 1) {
        ui_draw_world_map(world);
        return;
    }

    /* The ring covers [scroll_x, scroll_x+VIEW_W] x [scroll_y, scroll_y+VIEW_H].
     * The entering edge is the new offset column/row when the camera moved
     * right/down, or the new left/top column/row when it moved left/up. */
    c0 = world->scroll_x;
    c1 = (uint8_t)(world->scroll_x + WORLD_VIEW_W + 1);
    r0 = world->scroll_y;
    r1 = (uint8_t)(world->scroll_y + WORLD_VIEW_H + 1);
    if (dx > 0) c0 = (uint8_t)(world->scroll_x + WORLD_VIEW_W);
    else if (dx < 0) c1 = (uint8_t)(world->scroll_x + 1);
    if (dy > 0) r0 = (uint8_t)(world->scroll_y + WORLD_VIEW_H);
    else if (dy < 0) r1 = (uint8_t)(world->scroll_y + 1);
    ui_draw_world_rect(world, c0, c1, r0, r1);

#ifdef DEBUG_BUILD
    ui_refill_semantic(world);
#endif

    /* Sprite stays camera-relative (the BG scrolls under it). */
    ui_sprite_move((uint8_t)(world_player_px(world) - world->camera_px_x),
                   (uint8_t)(world_player_py(world) - world->camera_px_y));
}

void ui_update_camera(const World *world)
{
    if (!world) return;
    SCX_REG = world->camera_px_x;
    SCY_REG = world->camera_px_y;
}

/* Write one char to the HUD window tilemap (0x9C00) row `y` (0-5, displayed
 * at screen rows 12-17) and mirror it into the semantic g_ui_screen_buf.
 * The console font packs its glyphs starting at space, so char `ch` is tile
 * base + (ch - ' ').  Callers pass in-range coordinates (x < 20, y < 6). */
static void ui_hud_put_char(uint8_t x, uint8_t y, char ch)
{
    ((volatile uint8_t *)0x9C00)[y * 32 + x] = (uint8_t)(ui_font_tile_base + (uint8_t)(ch - ' '));
    g_ui_screen_buf[12 + y][x] = ch;
#ifdef DEBUG_BUILD
    g_hud_tilemap_mirror[y * 32 + x] = (uint8_t)(ui_font_tile_base + (uint8_t)(ch - ' '));
#endif
}

static void ui_hud_text_line(uint8_t y, const char *text, uint8_t max_chars)
{
    uint8_t i = 0;
    char ch;
    while (text && text[i] != '\0' && i < max_chars) {
        ch = text[i];
        ui_hud_put_char(i, y, ch);
        i++;
    }
    while (i < max_chars) {
        ui_hud_put_char(i, y, ' ');
        i++;
    }
}

/* Draw a value right-aligned in a 2-wide field (space padded) into the HUD
 * window row `y`. */
static void ui_hud_num2(uint8_t x, uint8_t y, uint8_t val)
{
    char c;
    if (val >= 10) {
        c = '0' + (val / 10);
    } else {
        c = ' ';
    }
    ui_hud_put_char(x, y, c);
    ui_hud_put_char(x + 1, y, '0' + (val % 10));
}

void ui_draw_overworld_hud(const World *world)
{
    const char *label;

    if (!world) return;

    /* The HUD lives in the WINDOW layer (0x9C00, VRAM bank 0).  Force the
     * VRAM bank select to 0 first so the tilemap writes land in bank 0 (not
     * the CGB attribute bank). */
    VBK_REG = 0;

    switch (world->map_id) {
        case MAP_TOWN:          label = "MAP: TOWN | HP:";  break;
        case MAP_FOREST:        label = "MAP: FORST| HP:";  break;
        case MAP_MOUNTAIN_PASS: label = "MAP: MOUNT| HP:";  break;
        case MAP_CASTLE:        label = "MAP: CASTL| HP:";  break;
        default:                label = "MAP: FIELD| HP:";  break;
    }

    /* The HUD lives in the WINDOW layer (0x9C00), so the SCX/SCY-scrolled
     * background map never carries it.  Window row y -> screen row 12+y. */
    ui_hud_text_line(0, "====================", 20);
    ui_hud_text_line(1, label, 15);
    ui_hud_num2(15, 1, world->player.hp);
    ui_hud_put_char(17, 1, '/');
    ui_hud_num2(18, 1, world->player.max_hp);
    ui_hud_text_line(2, "", 20);
    ui_hud_text_line(3, "", 20);
    ui_hud_text_line(4, "", 20);
    ui_hud_text_line(5, " [D-PAD] MOVE HERO", 20);
}

void ui_draw_world_full(const World *world)
{
    if (!world) return;
    ui_clear_screen();
    ui_draw_world_map(world);
    ui_draw_overworld_hud(world);
    ui_hud_show();
}

void ui_update_player_position(const World *world, uint8_t old_px, uint8_t old_py, uint8_t new_px, uint8_t new_py)
{
    /* The background never encodes the player (see ui_draw_world_map), so
     * there is nothing to erase/redraw at old_px/old_py any more -- moving
     * the OAM sprite is the whole update.  old_px/old_py are kept in the
     * signature so callers (RenderCache in overworld_screen.c) don't need
     * to change. */
    (void)old_px;
    (void)old_py;
    if (!world) return;
    ui_sprite_move(new_px, new_py);
}

static void ui_put_char(uint8_t x, uint8_t y, char ch)
{
    if (y < 18 && x < 20) {
        ((volatile uint8_t *)0x9C00)[y * 32 + x] =
            (uint8_t)(ui_font_tile_base + (uint8_t)(ch - ' '));
        g_ui_screen_buf[y][x] = ch;
    }
}

/* Draw a value right-aligned in a 2-wide field (space padded) at (x,y). */
static void ui_draw_num2(uint8_t x, uint8_t y, uint8_t val)
{
    char c;
    if (val >= 10) {
        c = '0' + (val / 10);
    } else {
        c = ' ';
    }
    ui_put_char(x, y, c);
    ui_put_char(x + 1, y, '0' + (val % 10));
}

/* Draw a battle HP line: "  HP: <hp>/<max>" at row y. */
static void ui_draw_hp_row(uint8_t y, uint8_t hp, uint8_t max_hp)
{
    ui_draw_text_line(0, y, "  HP: ", 6);
    ui_draw_num2(6, y, hp);
    ui_put_char(8, y, '/');
    ui_draw_num2(9, y, max_hp);
}

void ui_draw_battle_full(const Battle *battle)
{
    const uint8_t *bgmap;

    if (!battle) return;

    ui_clear_screen();

    /* Draw the battle background (4x2 tile strip) into the empty rows 3-4,
     * tiled horizontally across the 20-col screen.  Written directly to the
     * BG tilemap (0x9800) via the tile indices staged in ui_gfx_map(); the
     * semantic g_ui_screen_buf for those rows stays blank (spaces). */
    bgmap = ui_gfx_map();
    if (bgmap) {
        volatile uint8_t *tilemap = (volatile uint8_t *)0x9800;
        uint8_t y, x;
        VBK_REG = 0;
        for (y = 0; y < 2; y++) {
            for (x = 0; x < 20; x++) {
                tilemap[(3 + y) * 32 + x] =
                    (uint8_t)(UI_BATTLE_BG_TILE_BASE + bgmap[y * 4 + (x & 3)]);
            }
        }
    }

    ui_draw_text_line(0, 0, "====================", 20);
    ui_draw_text_line(0, 1, "    BATTLE ENCOUNTER", 20);
    ui_draw_text_line(0, 2, "====================", 20);

    ui_draw_text_line(0, 5, "  ENEMY: ", 9);
    ui_draw_text_line(9, 5, battle->enemy.name ? battle->enemy.name : "ENEMY", 8);
    ui_draw_hp_row(6, battle->enemy.hp, battle->enemy.max_hp);

    ui_draw_text_line(0, 9, "  HERO:", 7);
    ui_draw_hp_row(10, battle->player.hp, battle->player.max_hp);

    ui_draw_text_line(0, 13, "--------------------", 20);

    ui_update_battle(battle);

    /* Show the real hero sprite next to the "HERO:" label (text row 9,
     * col 15 -- where the old ASCII '@' sat), un-hiding it from the
     * screen_change() hide on the way in.  Only shadow OAM is written here;
     * the frame-boundary commit (ui_sprite_commit after vsync) DMAs it to
     * real OAM, so the sprite appears once the battle screen is drawn. */
    move_sprite(PLAYER_SPRITE_NUM, 128, 88);

    /* Show the enemy sprite on the battle background strip.  Slime/bat are
     * single 8x8 sprites; the boss spans a 2x2 grid.  Dropped into the
     * middle of the strip (screen pixels ~(72, 24)). */
    ui_enemy_sprite_show(battle->enemy_gfx, 72, 24);
}

void ui_update_battle(const Battle *battle)
{
    if (!battle) return;

    /* Keep HP readouts current as damage is dealt/received */
    ui_draw_hp_row(6, battle->enemy.hp, battle->enemy.max_hp);
    ui_draw_hp_row(10, battle->player.hp, battle->player.max_hp);

    if (battle->result == BATTLE_RESULT_VICTORY) {
        ui_draw_text_line(0, 15, " VICTORY! PRESS [A]", 20);
    } else if (battle->result == BATTLE_RESULT_DEFEAT) {
        ui_draw_text_line(0, 15, " DEFEATED! PRESS [A]", 20);
    } else if (battle->result == BATTLE_RESULT_FLED) {
        ui_draw_text_line(0, 15, " FLED! PRESS [A]", 20);
    } else if (battle->turn == BATTLE_TURN_PLAYER) {
        ui_draw_text_line(0, 15, " [A] ATTACK  [B] RUN", 20);
    } else {
        ui_draw_text_line(0, 15, " ENEMY TURN...", 20);
    }
}

/* Draw the window-frame tiles (ui_frame) around the box [c0,c1)x[r0,r1) in
 * the BG tilemap (0x9800).  The staged frame map gives the 3x3 layout
 * (corners, edges, center); the border is the outer ring and the interior
 * stays whatever the console drew (text).  The semantic g_ui_screen_buf is
 * untouched -- this is presentation only, over the existing console box. */
void ui_draw_dialogue(const DialogueState *dialogue)
{
    if (!dialogue || !dialogue->active) return;
    if (dialogue->current_line >= dialogue->line_count) return;

    /* Dialogue box occupies dedicated modal overlay region: rows 12-17 (6 rows, 20 columns) */
    ui_draw_text_line(0, 12, "+------------------+", 20);

    ui_put_char(0, 13, '|');
    ui_draw_text_line(1, 13, dialogue->speaker ? dialogue->speaker : "", 18);
    ui_put_char(19, 13, '|');

    ui_put_char(0, 14, '|');
    ui_draw_text_line(1, 14, dialogue->lines[dialogue->current_line], 18);
    ui_put_char(19, 14, '|');

    ui_put_char(0, 15, '|');
    ui_draw_text_line(1, 15, "", 18);
    ui_put_char(19, 15, '|');

    ui_put_char(0, 16, '|');
    ui_draw_text_line(1, 16, " [A] CONTINUE", 18);
    ui_put_char(19, 16, '|');

    ui_draw_text_line(0, 17, "+------------------+", 20);
}

void ui_draw_game_over(uint8_t choice)
{
    ui_clear_screen();
    ui_draw_text_line(0, 3, "    GAME OVER", 20);
    ui_draw_text_line(0, 8, "   CONTINUE?", 20);
    if (choice == 0) {
        ui_draw_text_line(0, 11, "> YES", 20);
        ui_draw_text_line(0, 12, "  NO", 20);
    } else {
        ui_draw_text_line(0, 11, "  YES", 20);
        ui_draw_text_line(0, 12, "> NO", 20);
    }
    ui_draw_text_line(0, 16, " [A] CONFIRM", 20);
}

void ui_draw_thanks(void)
{
    ui_clear_screen();
    ui_draw_text_line(0, 8, " THANKS FOR PLAYING!", 20);
}

#ifdef DEBUG_BUILD
void ui_draw_font_test(void)
{
    ui_clear_screen();
    ui_draw_text_line(0, 0, "=== FONT TEST ===", 20);
    ui_draw_text_line(0, 2, "ABCDEFGHIJKLMNOPQRST", 20);
    ui_draw_text_line(0, 4, "UVWXYZ", 20);
    ui_draw_text_line(0, 6, "abcdefghijklmnopqrst", 20);
    ui_draw_text_line(0, 8, "uvwxyz", 20);
    ui_draw_text_line(0, 10, "0123456789", 20);
    ui_draw_text_line(0, 12, "!?.,:-'[]+=", 20);
}
#endif
