/* Generated by tools/png2gb.py from enemy_bat.png (8x8px, 1 tile). */
const uint8_t enemy_bat[16] = {
    0x81, 0x81,   /* #      # */
    0xC3, 0xC3,   /* ##    ## */
    0xE7, 0xE7,   /* ###  ### */
    0x7E, 0x7E,   /*  ######  */
    0x3C, 0x3C,   /*   ####   */
    0x42, 0x42,   /*  #    #  */
    0x00, 0x00,   /*          */
    0x00, 0x00   /*          */
};
