/* Generated by tools/png2gb.py from enemy_slime.png (8x8px, 1 tile). */
const uint8_t enemy_slime[16] = {
    0x3C, 0x3C,   /*   ####   */
    0x42, 0x7E,   /*  #::::#  */
    0x81, 0xE7,   /* #::  ::# */
    0x81, 0xFF,   /* #::::::# */
    0x81, 0xFF,   /* #::::::# */
    0x81, 0xFF,   /* #::::::# */
    0x42, 0x7E,   /*  #::::#  */
    0x3C, 0x3C   /*   ####   */
};
