/* Generated by tools/png2gb.py from npc_shopkeeper.png (8x8px, 1 tile). */
const uint8_t npc_shopkeeper[16] = {
    0x7E, 0x7E,   /*  ######  */
    0x81, 0x81,   /* #      # */
    0x80, 0x80,   /* #        */
    0x7E, 0x7E,   /*  ######  */
    0x01, 0x01,   /*        # */
    0x01, 0x01,   /*        # */
    0x81, 0x81,   /* #      # */
    0x7E, 0x7E   /*  ######  */
};
