/* Generated by tools/png2gb.py from npc_mayor.png (8x8px, 1 tile). */
const uint8_t npc_mayor[16] = {
    0x81, 0x81,   /* #      # */
    0xC3, 0xC3,   /* ##    ## */
    0xA5, 0xA5,   /* # #  # # */
    0x99, 0x99,   /* #  ##  # */
    0x81, 0x81,   /* #      # */
    0x81, 0x81,   /* #      # */
    0x81, 0x81,   /* #      # */
    0x81, 0x81   /* #      # */
};
