/* Generated by tools/png2gb.py from npc_amulet.png (8x8px, 1 tile). */
const uint8_t npc_amulet[16] = {
    0x7E, 0x7E,   /*  ######  */
    0x81, 0x81,   /* #      # */
    0x01, 0x01,   /*        # */
    0x06, 0x06,   /*      ##  */
    0x18, 0x18,   /*    ##    */
    0x20, 0x20,   /*   #      */
    0x00, 0x00,   /*          */
    0x20, 0x20   /*   #      */
};
