/* Generated by tools/png2gb.py from npc_guard.png (8x8px, 1 tile). */
const uint8_t npc_guard[16] = {
    0x7E, 0x7E,   /*  ######  */
    0x81, 0x81,   /* #      # */
    0x80, 0x80,   /* #        */
    0x80, 0x80,   /* #        */
    0x87, 0x87,   /* #    ### */
    0x81, 0x81,   /* #      # */
    0x81, 0x81,   /* #      # */
    0x7E, 0x7E   /*  ######  */
};
