/* Generated by tools/png2gb.py from npc_merchant.png (8x8px, 1 tile). */
const uint8_t npc_merchant[16] = {
    0xFF, 0xFF,   /* ######## */
    0x80, 0x80,   /* #        */
    0x80, 0x80,   /* #        */
    0xFE, 0xFE,   /* #######  */
    0x80, 0x80,   /* #        */
    0x80, 0x80,   /* #        */
    0x80, 0x80,   /* #        */
    0xFF, 0xFF   /* ######## */
};
