/* Generated by tools/png2gb.py from player_demo.png (8x8px, 1 tile). */
static const uint8_t player_sprite_tile[16] = {
    0x3C, 0x3C,   /*   ####   */
    0x7E, 0x7E,   /*  ######  */
    0x66, 0x66,   /*  ##  ##  */
    0x7E, 0x7E,   /*  ######  */
    0x3C, 0x3C,   /*   ####   */
    0x18, 0x18,   /*    ##    */
    0x3C, 0x3C,   /*   ####   */
    0x7E, 0x7E   /*  ######  */
};
